Progetto laboratorio di programmazione. Gruppo: Nicolò Cioni, Rossano Gilioli e Salvatore Russo. Dataset scelto : dataset n 1

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option('display.max_rows', 70)
test= pd.read_csv("/content/sample_data/1.test_convertito_numerici.csv", sep=",")
test_non = pd.read_csv("/content/sample_data/1.test_non_convertito.csv", sep=",")
train_non = pd.read_csv("/content/sample_data/1.train_non_convertito.csv", sep=",")
train = pd.read_csv("/content/sample_data/1.train_convertito_numerici.csv", sep=",")

Quante righe e colonne sono presenti nei due dataset? I valori sono per lo più numerici o categorici e tra le righe sono poi presenti valori nulli?

In [ ]:
train

hotel  is_canceled  lead_time  arrival_date_year  arrival_date_month  \
0          1            0        109               2016                   1   
1          1            0        109               2016                   1   
2          1            1          2               2016                   1   
3          1            0         88               2016                   1   
4          1            1         20               2016                   1   
...      ...          ...        ...                ...                 ...   
56702      0            0         17               2016                  12   
56703      0            0        177               2016                  12   
56704      0            0        107               2016                  12   
56705      0            0        310               2016                  12   
56706      0            0        310               2016                  12   

       arrival_date_week_number  arrival_date_day_of_month  \
0                             1                          1   
1                             1                          1   
2                             1                          1   
3                             1                          1   
4                             1                          1   
...                         ...                        ...   
56702                        53                         30   
56703                        53                         30   
56704                        53                         31   
56705                        53                         27   
56706                        53                         27   

       stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
0                            0                     1       2  ...   
1                            0                     1       2  ...   
2                            0                     1       2  ...   
3                            0                     2       2  ...   
4                            0                     2       2  ...   
...                        ...                   ...     ...  ...   
56702                        2                     5       2  ...   
56703                        2                     5       0  ...   
56704                        2                     5       2  ...   
56705                        2                    10       2  ...   
56706                        2                    10       2  ...   

       assigned_room_type  booking_changes  deposit_type  agent  company  \
0                       3                0             0  240.0     -1.0   
1                       7                0             0  240.0     -1.0   
2                       3                0             0  240.0     -1.0   
3                       3                0             0  241.0     -1.0   
4                       6                0             0  240.0     -1.0   
...                   ...              ...           ...    ...      ...   
56702                   0                0             0    9.0     -1.0   
56703                   9                2             0   -1.0     -1.0   
56704                   1                0             0   28.0     -1.0   
56705                   0                2             0    9.0     -1.0   
56706                   0                2             0    9.0     -1.0   

       days_in_waiting_list  customer_type     adr  \
0                         0              3   59.94   
1                         0              3  116.10   
2                         0              2   89.00   
3                         0              2   73.46   
4                         0              2  119.00   
...                     ...            ...     ...   
56702                     0              2   90.34   
56703                     0              2    1.29   
56704                     0              2  103.57   
56705                     0    

In [ ]:
test

hotel  is_canceled  lead_time  arrival_date_year  arrival_date_month  \
0          1            1         74               2017                   1   
1          1            1         62               2017                   1   
2          1            1         62               2017                   1   
3          1            1         62               2017                   1   
4          1            1         71               2017                   1   
...      ...          ...        ...                ...                 ...   
40682      0            0         23               2017                   8   
40683      0            0        102               2017                   8   
40684      0            0         34               2017                   8   
40685      0            0        109               2017                   8   
40686      0            0        205               2017                   8   

       arrival_date_week_number  arrival_date_day_of_month  \
0                             1                          1   
1                             1                          1   
2                             1                          1   
3                             1                          1   
4                             1                          1   
...                         ...                        ...   
40682                        35                         30   
40683                        35                         31   
40684                        35                         31   
40685                        35                         31   
40686                        35                         29   

       stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
0                            1                     0       2  ...   
1                            2                     2       2  ...   
2                            2                     2       2  ...   
3                            2                     2       2  ...   
4                            2                     2       1  ...   
...                        ...                   ...     ...  ...   
40682                        2                     5       2  ...   
40683                        2                     5       3  ...   
40684                        2                     5       2  ...   
40685                        2                     5       2  ...   
40686                        2                     7       2  ...   

       assigned_room_type  booking_changes  deposit_type  agent  company  \
0                       0                0             0    5.0     -1.0   
1                       0                0             0  240.0     -1.0   
2                       0                0             0  240.0     -1.0   
3                       0                0             0  240.0     -1.0   
4                       0                0             0  241.0     -1.0   
...                   ...              ...           ...    ...      ...   
40682                   0                0             0  394.0     -1.0   
40683                   4                0             0    9.0     -1.0   
40684                   3                0             0    9.0     -1.0   
40685                   0                0             0   89.0     -1.0   
40686                   0                0             0    9.0     -1.0   

       days_in_waiting_list  customer_type     adr  \
0                         0              2   57.60   
1                         0              2   51.50   
2                         0              2   51.50   
3                         0              2   51.50   
4                         0              2   32.22   
...                     ...            ...     ...   
40682                     0              2   96.14   
40683                     0              2  225.43   
40684                     0              2  157.71   
40685                     0    

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56707 entries, 0 to 56706
Data columns (total 30 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   hotel                           56707 non-null  int64  
 1   is_canceled                     56707 non-null  int64  
 2   lead_time                       56707 non-null  int64  
 3   arrival_date_year               56707 non-null  int64  
 4   arrival_date_month              56707 non-null  int64  
 5   arrival_date_week_number        56707 non-null  int64  
 6   arrival_date_day_of_month       56707 non-null  int64  
 7   stays_in_weekend_nights         56707 non-null  int64  
 8   stays_in_week_nights            56707 non-null  int64  
 9   adults                          56707 non-null  int64  
 10  children                        56707 non-null  float64
 11  babies                          56707 non-null  int64  
 12  meal                            

In [ ]:
tot_train = 56708

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40687 entries, 0 to 40686
Data columns (total 30 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   hotel                           40687 non-null  int64  
 1   is_canceled                     40687 non-null  int64  
 2   lead_time                       40687 non-null  int64  
 3   arrival_date_year               40687 non-null  int64  
 4   arrival_date_month              40687 non-null  int64  
 5   arrival_date_week_number        40687 non-null  int64  
 6   arrival_date_day_of_month       40687 non-null  int64  
 7   stays_in_weekend_nights         40687 non-null  int64  
 8   stays_in_week_nights            40687 non-null  int64  
 9   adults                          40687 non-null  int64  
 10  children                        40687 non-null  float64
 11  babies                          40687 non-null  int64  
 12  meal                            

In [ ]:
tot_test = 40687

In [ ]:
test.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                         

In [ ]:
train.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                         

In [ ]:
train["is_canceled"].mean()

0.3586329730015695

In [ ]:
test["is_canceled"].mean()

0.38697864182662767

Nel "Train dataset" sono presenti 56707 righe mentre nel "Test Dataset" 40687. Le colonne, invece, sono 30 per entrambi. I valori sono perlopiù categorici (18/30), infatti,  molti dei valori segnati come "int" in realtà sono la conversione in numero di "Si" e "No"(es: "is_canceled") . In entrambi i dateset non sono presenti valori nulli. La media delle cancellazioni è del 36% nel train dataset e del 39% nel secondo.

Come si distribuisce il valore relativo al numero di persone? Quante prenotazioni includono bambini e quanti ospiti sono, invece,  da soli?

In [ ]:
train["persone"] = train["babies"] + train["children"] + train["adults"]
print(train["persone"].mean())
test["persone"] = train["babies"] + train["children"] + train["adults"]
print(test["persone"].mean())

1.9633378595235156
1.9511637623811044


In [ ]:
train.groupby(train["babies"]).count()

hotel  is_canceled  lead_time  arrival_date_year  arrival_date_month  \
babies                                                                         
0       56261        56261      56261              56261               56261   
1         437          437        437                437                 437   
2           8            8          8                  8                   8   
10          1            1          1                  1                   1   

        arrival_date_week_number  arrival_date_day_of_month  \
babies                                                        
0                          56261                      56261   
1                            437                        437   
2                              8                          8   
10                             1                          1   

        stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
babies                                                         ...   
0                         56261                 56261   56261  ...   
1                           437                   437     437  ...   
2                             8                     8       8  ...   
10                            1                     1       1  ...   

        booking_changes  deposit_type  agent  company  days_in_waiting_list  \
babies                                                                        
0                 56261         56261  56261    56261                 56261   
1                   437           437    437      437                   437   
2                     8             8      8        8                     8   
10                    1             1      1        1                     1   

        customer_type    adr  required_car_parking_spaces  \
babies                                                      
0               56261  56261                        56261   
1                 437    437                          437   
2                   8      8                            8   
10                  1      1                            1   

        total_of_special_requests  persone  
babies                                      
0                           56261    56261  
1                             437      437  
2                               8        8  
10                              1        1  

[4 rows x 30 columns]

In [ ]:
#unisco colonne children e babies
train["colonna_bambini"] = train["babies"] + train["children"]
train.groupby(train["colonna_bambini"]).count()

hotel  is_canceled  lead_time  arrival_date_year  \
colonna_bambini                                                     
0.0              52211        52211      52211              52211   
1.0               2678         2678       2678               2678   
2.0               1768         1768       1768               1768   
3.0                 49           49         49                 49   
10.0                 1            1          1                  1   

                 arrival_date_month  arrival_date_week_number  \
colonna_bambini                                                 
0.0                           52211                     52211   
1.0                            2678                      2678   
2.0                            1768                      1768   
3.0                              49                        49   
10.0                              1                         1   

                 arrival_date_day_of_month  stays_in_weekend_nights  \
colonna_bambini                                                       
0.0                                  52211                    52211   
1.0                                   2678                     2678   
2.0                                   1768                     1768   
3.0                                     49                       49   
10.0                                     1                        1   

                 stays_in_week_nights  adults  ...  booking_changes  \
colonna_bambini                                ...                    
0.0                             52211   52211  ...            52211   
1.0                              2678    2678  ...             2678   
2.0                              1768    1768  ...             1768   
3.0                                49      49  ...               49   
10.0                                1       1  ...                1   

                 deposit_type  agent  company  days_in_waiting_list  \
colonna_bambini                                                       
0.0                     52211  52211    52211                 52211   
1.0                      2678   2678     2678                  2678   
2.0                      1768   1768     1768                  1768   
3.0                        49     49       49                    49   
10.0                        1      1        1                     1   

                 customer_type    adr  required_car_parking_spaces  \
colonna_bambini                                                      
0.0                      52211  52211                        52211   
1.0                       2678   2678                         2678   
2.0                       1768   1768                         1768   
3.0                         49     49                           49   
10.0                         1      1                            1   

                 total_of_special_requests  persone  
colonna_bambini                                      
0.0                                  52211    52211  
1.0                                   2678     2678  
2.0                                   1768     1768  
3.0                                     49       49  
10.0                                     1        1  

[5 rows x 31 columns]

In [ ]:
test["colonna_bambini"] = test["babies"] + test["children"]
test.groupby(test["colonna_bambini"]).count()

hotel  is_canceled  lead_time  arrival_date_year  \
colonna_bambini                                                     
0.0              36941        36941      36941              36941   
1.0               2136         2136       2136               2136   
2.0               1565         1565       1565               1565   
3.0                 45           45         45                 45   

                 arrival_date_month  arrival_date_week_number  \
colonna_bambini                                                 
0.0                           36941                     36941   
1.0                            2136                      2136   
2.0                            1565                      1565   
3.0                              45                        45   

                 arrival_date_day_of_month  stays_in_weekend_nights  \
colonna_bambini                                                       
0.0                                  36941                    36941   
1.0                                   2136                     2136   
2.0                                   1565                     1565   
3.0                                     45                       45   

                 stays_in_week_nights  adults  ...  booking_changes  \
colonna_bambini                                ...                    
0.0                             36941   36941  ...            36941   
1.0                              2136    2136  ...             2136   
2.0                              1565    1565  ...             1565   
3.0                                45      45  ...               45   

                 deposit_type  agent  company  days_in_waiting_list  \
colonna_bambini                                                       
0.0                     36941  36941    36941                 36941   
1.0                      2136   2136     2136                  2136   
2.0                      1565   1565     1565                  1565   
3.0                        45     45       45                    45   

                 customer_type    adr  required_car_parking_spaces  \
colonna_bambini                                                      
0.0                      36941  36941                        36941   
1.0                       2136   2136                         2136   
2.0                       1565   1565                         1565   
3.0                         45     45                           45   

                 total_of_special_requests  persone  
colonna_bambini                                      
0.0                                  36941    36941  
1.0                                   2136     2136  
2.0                                   1565     1565  
3.0                                     45       45  

[4 rows x 31 columns]

In [ ]:
#media cancellazioni in base al numero di bambini
train.groupby(train["colonna_bambini"])["is_canceled"].mean()

colonna_bambini
0.0     0.360020
1.0     0.305078
2.0     0.400452
3.0     0.306122
10.0    0.000000
Name: is_canceled, dtype: float64

In [ ]:
test.groupby(test["colonna_bambini"])["is_canceled"].mean()

colonna_bambini
0.0    0.385859
1.0    0.352060
2.0    0.466454
3.0    0.200000
Name: is_canceled, dtype: float64

In [ ]:
train[train["colonna_bambini"] > 9.00]

hotel  is_canceled  lead_time  arrival_date_year  arrival_date_month  \
18765      0            0         37               2016                   1   

       arrival_date_week_number  arrival_date_day_of_month  \
18765                         3                         12   

       stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
18765                        0                     2       2  ...   

       deposit_type  agent  company  days_in_waiting_list  customer_type  \
18765             0    9.0     -1.0                     0              2   

         adr  required_car_parking_spaces  total_of_special_requests  persone  \
18765  84.45                            0                          1     12.0   

       colonna_bambini  
18765             10.0  

[1 rows x 32 columns]

In [ ]:
train.groupby(train["persone"]).count()


hotel  is_canceled  lead_time  arrival_date_year  arrival_date_month  \
persone                                                                         
0.0         84           84         84                 84                  84   
1.0      10967        10967      10967              10967               10967   
2.0      38563        38563      38563              38563               38563   
3.0       5189         5189       5189               5189                5189   
4.0       1852         1852       1852               1852                1852   
5.0         51           51         51                 51                  51   
12.0         1            1          1                  1                   1   

         arrival_date_week_number  arrival_date_day_of_month  \
persone                                                        
0.0                            84                         84   
1.0                         10967                      10967   
2.0                         38563                      38563   
3.0                          5189                       5189   
4.0                          1852                       1852   
5.0                            51                         51   
12.0                            1                          1   

         stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
persone                                                         ...   
0.0                           84                    84      84  ...   
1.0                        10967                 10967   10967  ...   
2.0                        38563                 38563   38563  ...   
3.0                         5189                  5189    5189  ...   
4.0                         1852                  1852    1852  ...   
5.0                           51                    51      51  ...   
12.0                           1                     1       1  ...   

         booking_changes  deposit_type  agent  company  days_in_waiting_list  \
persone                                                                        
0.0                   84            84     84       84                    84   
1.0                10967         10967  10967    10967                 10967   
2.0                38563         38563  38563    38563                 38563   
3.0                 5189          5189   5189     5189                  5189   
4.0                 1852          1852   1852     1852                  1852   
5.0                   51            51     51       51                    51   
12.0                   1             1      1        1                     1   

         customer_type    adr  required_car_parking_spaces  \
persone                                                      
0.0                 84     84                           84   
1.0              10967  10967                        10967   
2.0              38563  38563                        38563   
3.0               5189   5189                         5189   
4.0               1852   1852                         1852   
5.0                 51     51                           51   
12.0                 1      1                            1   

         total_of_special_requests  colonna_bambini  
persone                                              
0.0                             84               84  
1.0                          10967            10967  
2.0                          38563            38563  
3.0                           5189             5189  
4.0                           1852             1852  
5.0                             51               51  
12.0                             1                1  

[7 rows x 31 columns]

In [ ]:
test.groupby(test["persone"]).count()

hotel  is_canceled  lead_time  arrival_date_year  arrival_date_month  \
persone                                                                         
0.0         27           27         27                 27                  27   
1.0       7911         7911       7911               7911                7911   
2.0      28241        28241      28241              28241               28241   
3.0       3081         3081       3081               3081                3081   
4.0       1391         1391       1391               1391                1391   
5.0         35           35         35                 35                  35   
12.0         1            1          1                  1                   1   

         arrival_date_week_number  arrival_date_day_of_month  \
persone                                                        
0.0                            27                         27   
1.0                          7911                       7911   
2.0                         28241                      28241   
3.0                          3081                       3081   
4.0                          1391                       1391   
5.0                            35                         35   
12.0                            1                          1   

         stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
persone                                                         ...   
0.0                           27                    27      27  ...   
1.0                         7911                  7911    7911  ...   
2.0                        28241                 28241   28241  ...   
3.0                         3081                  3081    3081  ...   
4.0                         1391                  1391    1391  ...   
5.0                           35                    35      35  ...   
12.0                           1                     1       1  ...   

         booking_changes  deposit_type  agent  company  days_in_waiting_list  \
persone                                                                        
0.0                   27            27     27       27                    27   
1.0                 7911          7911   7911     7911                  7911   
2.0                28241         28241  28241    28241                 28241   
3.0                 3081          3081   3081     3081                  3081   
4.0                 1391          1391   1391     1391                  1391   
5.0                   35            35     35       35                    35   
12.0                   1             1      1        1                     1   

         customer_type    adr  required_car_parking_spaces  \
persone                                                      
0.0                 27     27                           27   
1.0               7911   7911                         7911   
2.0              28241  28241                        28241   
3.0               3081   3081                         3081   
4.0               1391   1391                         1391   
5.0                 35     35                           35   
12.0                 1      1                            1   

         total_of_special_requests  colonna_bambini  
persone                                              
0.0                             27               27  
1.0                           7911             7911  
2.0                          28241            28241  
3.0                           3081             3081  
4.0                           1391             1391  
5.0                             35               35  
12.0                             1                1  

[7 rows x 31 columns]

In [ ]:
train.groupby(train["persone"])["is_canceled"].mean()

persone
0.0     0.154762
1.0     0.301176
2.0     0.380468
3.0     0.305454
4.0     0.405508
5.0     0.254902
12.0    0.000000
Name: is_canceled, dtype: float64

In [ ]:
test.groupby(test["persone"])["is_canceled"].mean()

persone
0.0     0.296296
1.0     0.307926
2.0     0.409865
3.0     0.344369
4.0     0.471603
5.0     0.228571
12.0    1.000000
Name: is_canceled, dtype: float64

La media del numero di persone è di circa 2 persone in entrambi i dataset.
Il numero di prenotazioni composte da un numero qualsiasi di adulti con almeno un bambino ("babies" e/o "children") è relativamente basso in entrambi i dataset (poco più di 2000 casi). Il numero massimo di bambini è di 10 raggiunto però in un singolo caso. Escludendo quello il massimo di bambini a seguito è di 3. Le cancellazioni aumentano all'aumentare del numero di bambini in entrambi i dataset (le prenotazioni con almeno 3 bambini sono in numero così ridotto da non essere rilevanti). Escludendo suddetto caso estremo il numero massimo di persone per una singola camera è 5, anche il numero di queste non sembra avere particolare impatto sulle cancellazioni. In entrambi i dataset poi sono presenti valori anomali corrispondenti a 0 persone per camera (84 nel train e 27 nel test).
Il numero di viaggiatori "solitari" è invece copicuo e simile in entrambi i dataset.
Il numero di adulti per prenotazione varia da un minomo di 1 fino a un massimo di 4.



Come si distrubuisce il numero delle prenotazioni nei mesi dell'anno e la media delle cancellazioni?

In [ ]:
train.groupby(train["arrival_date_month"]).count()

hotel  is_canceled  lead_time  arrival_date_year  \
arrival_date_month                                                     
1                    2248         2248       2248               2248   
2                    3891         3891       3891               3891   
3                    4824         4824       4824               4824   
4                    5428         5428       5428               5428   
5                    5478         5478       5478               5478   
6                    5292         5292       5292               5292   
7                    4572         4572       4572               4572   
8                    5063         5063       5063               5063   
9                    5394         5394       5394               5394   
10                   6203         6203       6203               6203   
11                   4454         4454       4454               4454   
12                   3860         3860       3860               3860   

                    arrival_date_week_number  arrival_date_day_of_month  \
arrival_date_month                                                        
1                                       2248                       2248   
2                                       3891                       3891   
3                                       4824                       4824   
4                                       5428                       5428   
5                                       5478                       5478   
6                                       5292                       5292   
7                                       4572                       4572   
8                                       5063                       5063   
9                                       5394                       5394   
10                                      6203                       6203   
11                                      4454                       4454   
12                                      3860                       3860   

                    stays_in_weekend_nights  stays_in_week_nights  adults  \
arrival_date_month                                                          
1                                      2248                  2248    2248   
2                                      3891                  3891    3891   
3                                      4824                  4824    4824   
4                                      5428                  5428    5428   
5                                      5478                  5478    5478   
6                                      5292                  5292    5292   
7                                      4572                  4572    4572   
8                                      5063                  5063    5063   
9                                      5394                  5394    5394   
10                                     6203                  6203    6203   
11                                     4454                  4454    4454   
12                                     3860                  3860    3860   

                    children  ...  deposit_type  agent  company  \
arrival_date_month            ...                                 
1                       2248  ...          2248   2248     2248   
2                       3891  ...          3891   3891     3891   
3                       4824  ...          4824   4824     4824   
4                       5428  ...          5428   5428     5428   
5                       5478  ...          5478   5478     5478   
6                       5292  ...          5292   5292     5292   
7                       4572  ...          4572   4572     4572   
8                       5063  ...          5063   5063     5063   
9                       5394  ...          5394   5394     5394   
10                      6203  ...          6203   6203     6203   
11                      4454  ...          4454   4454     4454   
12        

In [ ]:
test.groupby(test["arrival_date_month"]).count()

hotel  is_canceled  lead_time  arrival_date_year  \
arrival_date_month                                                     
1                    3681         3681       3681               3681   
2                    4177         4177       4177               4177   
3                    4970         4970       4970               4970   
4                    5661         5661       5661               5661   
5                    6313         6313       6313               6313   
6                    5647         5647       5647               5647   
7                    5313         5313       5313               5313   
8                    4925         4925       4925               4925   

                    arrival_date_week_number  arrival_date_day_of_month  \
arrival_date_month                                                        
1                                       3681                       3681   
2                                       4177                       4177   
3                                       4970                       4970   
4                                       5661                       5661   
5                                       6313                       6313   
6                                       5647                       5647   
7                                       5313                       5313   
8                                       4925                       4925   

                    stays_in_weekend_nights  stays_in_week_nights  adults  \
arrival_date_month                                                          
1                                      3681                  3681    3681   
2                                      4177                  4177    4177   
3                                      4970                  4970    4970   
4                                      5661                  5661    5661   
5                                      6313                  6313    6313   
6                                      5647                  5647    5647   
7                                      5313                  5313    5313   
8                                      4925                  4925    4925   

                    children  ...  deposit_type  agent  company  \
arrival_date_month            ...                                 
1                       3681  ...          3681   3681     3681   
2                       4177  ...          4177   4177     4177   
3                       4970  ...          4970   4970     4970   
4                       5661  ...          5661   5661     5661   
5                       6313  ...          6313   6313     6313   
6                       5647  ...          5647   5647     5647   
7                       5313  ...          5313   5313     5313   
8                       4925  ...          4925   4925     4925   

                    days_in_waiting_list  customer_type   adr  \
arrival_date_month                                              
1                                   3681           3681  3681   
2                                   4177           4177  4177   
3                                   4970           4970  4970   
4                                   5661           5661  5661   
5                                   6313           6313  6313   
6                                   5647           5647  5647   
7                                   5313           5313  5313   
8                                   4925           4925  4925   

                    required_car_parking_spaces  total_of_special_requests  \
arrival_date_month                                                           
1                                          3681                       3681   
2                                          4177                       4177   
3                                          4970                       4970   
4                                          5661                  

In [ ]:
train.groupby(train["arrival_date_month"])["persone"].mean()

arrival_date_month
1     1.705961
2     1.854279
3     1.919776
4     1.929071
5     1.902154
6     1.908730
7     2.209318
8     2.291132
9     1.972562
10    1.928099
11    1.797261
12    2.001554
Name: persone, dtype: float64

In [ ]:
test.groupby(test["arrival_date_month"])["persone"].mean()

arrival_date_month
1    2.077153
2    2.028489
3    1.932998
4    1.894365
5    1.904324
6    1.853728
7    1.952005
8    2.045888
Name: persone, dtype: float64

In [ ]:
#media cancellazioni in base al mese di arrivo
train.groupby(train["arrival_date_month"])["is_canceled"].mean()

arrival_date_month
1     0.247776
2     0.343613
3     0.306177
4     0.379698
5     0.349580
6     0.396070
7     0.327865
8     0.360458
9     0.374861
10    0.405288
11    0.367310
12    0.362176
Name: is_canceled, dtype: float64

In [ ]:
test.groupby(test["arrival_date_month"])["is_canceled"].mean()

arrival_date_month
1    0.339582
2    0.325353
3    0.336419
4    0.435082
5    0.437510
6    0.431911
7    0.373424
8    0.368731
Name: is_canceled, dtype: float64

I due dataset differiscono per il numero di mesi tenuti in considerazione: il testdataset, infatti, prende in considerazione soltanto i mesi da gennaio a agosto.
Il mese che ha riscontrato più prenotazioni nel traindataset è quello di ottobre, tuttavia le prenotazioni sembrano abbastanza equamente suddivise, fatta eccezione per gennaio dove si è riscontrato un valore notevolmente più basso in entrambi i dataset (anche se più marcato nel train). Nel test dataset si ha poi un aumento non trascurabile di prenotazioni nel meese di maggio, non presente invece nel train.
La media realtiva al numero di persone in ognuno dei mesi dell'anno è in linea con quella generale dei due dataset.
Quella delle cancellazioni invece risulta più altalentante con valori che si distanziano notevolmente dalla media generale (es: gennaio, nel train dataset, si distanzia di 11 punti percentuali).

Come si sono divisi i casi in base al segmento di mercaro? Come cambia la media relativa al numero di cancellazioni?

In [ ]:
train_non.groupby(train_non["market_segment"]).count()

hotel  is_canceled  lead_time  arrival_date_year  \
market_segment                                                     
Aviation          127          127        127                127   
Complementary     364          364        364                364   
Corporate        2562         2562       2562               2562   
Direct           5663         5663       5663               5663   
Groups           7857         7857       7857               7857   
Offline TA/TO   12473        12473      12473              12473   
Online TA       27661        27661      27661              27661   

                arrival_date_month  arrival_date_week_number  \
market_segment                                                 
Aviation                       127                       127   
Complementary                  364                       364   
Corporate                     2562                      2562   
Direct                        5663                      5663   
Groups                        7857                      7857   
Offline TA/TO                12473                     12473   
Online TA                    27661                     27661   

                arrival_date_day_of_month  stays_in_weekend_nights  \
market_segment                                                       
Aviation                              127                      127   
Complementary                         364                      364   
Corporate                            2562                     2562   
Direct                               5663                     5663   
Groups                               7857                     7857   
Offline TA/TO                       12473                    12473   
Online TA                           27661                    27661   

                stays_in_week_nights  adults  ...  assigned_room_type  \
market_segment                                ...                       
Aviation                         127     127  ...                 127   
Complementary                    364     364  ...                 364   
Corporate                       2562    2562  ...                2562   
Direct                          5663    5663  ...                5663   
Groups                          7857    7857  ...                7857   
Offline TA/TO                  12473   12473  ...               12473   
Online TA                      27661   27661  ...               27661   

                booking_changes  deposit_type  agent  company  \
market_segment                                                  
Aviation                    127           127    127      127   
Complementary               364           364    364      364   
Corporate                  2562          2562   2562     2562   
Direct                     5663          5663   5663     5663   
Groups                     7857          7857   7857     7857   
Offline TA/TO             12473         12473  12473    12473   
Online TA                 27661         27661  27661    27661   

                days_in_waiting_list  customer_type    adr  \
market_segment                                               
Aviation                         127            127    127   
Complementary                    364            364    364   
Corporate                       2562           2562   2562   
Direct                          5663           5663   5663   
Groups                          7857           7857   7857   
Offline TA/TO                  12473          12473  12473   
Online TA                      27661          27661  27661   

                required_car_parking_spaces  total_of_special_requests  
market_segment                                                          
Aviation                                127                        127  
Complementary                           364                        364  
Corporate                              2562                       2562  
Direct                     

In [ ]:
test_non.groupby(test_non["market_segment"]).count()

hotel  is_canceled  lead_time  arrival_date_year  \
market_segment                                                     
Aviation          110          110        110                110   
Complementary     214          214        214                214   
Corporate        1562         1562       1562               1562   
Direct           4629         4629       4629               4629   
Groups           5854         5854       5854               5854   
Offline TA/TO    5667         5667       5667               5667   
Online TA       22651        22651      22651              22651   

                arrival_date_month  arrival_date_week_number  \
market_segment                                                 
Aviation                       110                       110   
Complementary                  214                       214   
Corporate                     1562                      1562   
Direct                        4629                      4629   
Groups                        5854                      5854   
Offline TA/TO                 5667                      5667   
Online TA                    22651                     22651   

                arrival_date_day_of_month  stays_in_weekend_nights  \
market_segment                                                       
Aviation                              110                      110   
Complementary                         214                      214   
Corporate                            1562                     1562   
Direct                               4629                     4629   
Groups                               5854                     5854   
Offline TA/TO                        5667                     5667   
Online TA                           22651                    22651   

                stays_in_week_nights  adults  ...  assigned_room_type  \
market_segment                                ...                       
Aviation                         110     110  ...                 110   
Complementary                    214     214  ...                 214   
Corporate                       1562    1562  ...                1562   
Direct                          4629    4629  ...                4629   
Groups                          5854    5854  ...                5854   
Offline TA/TO                   5667    5667  ...                5667   
Online TA                      22651   22651  ...               22651   

                booking_changes  deposit_type  agent  company  \
market_segment                                                  
Aviation                    110           110    110      110   
Complementary               214           214    214      214   
Corporate                  1562          1562   1562     1562   
Direct                     4629          4629   4629     4629   
Groups                     5854          5854   5854     5854   
Offline TA/TO              5667          5667   5667     5667   
Online TA                 22651         22651  22651    22651   

                days_in_waiting_list  customer_type    adr  \
market_segment                                               
Aviation                         110            110    110   
Complementary                    214            214    214   
Corporate                       1562           1562   1562   
Direct                          4629           4629   4629   
Groups                          5854           5854   5854   
Offline TA/TO                   5667           5667   5667   
Online TA                      22651          22651  22651   

                required_car_parking_spaces  total_of_special_requests  
market_segment                                                          
Aviation                                110                        110  
Complementary                           214                        214  
Corporate                              1562                       1562  
Direct                     

In [ ]:
test_non.groupby(test_non["market_segment"])["is_canceled"].mean()

market_segment
Aviation         0.209091
Complementary    0.163551
Corporate        0.254802
Direct           0.154677
Groups           0.581141
Offline TA/TO    0.337745
Online TA        0.408680
Name: is_canceled, dtype: float64

In [ ]:
train_non.groupby(train_non["market_segment"])["is_canceled"].mean()

market_segment
Aviation         0.228346
Complementary    0.129121
Corporate        0.146370
Direct           0.153099
Groups           0.617539
Offline TA/TO    0.347150
Online TA        0.355627
Name: is_canceled, dtype: float64

I valori relativi ai canali di distribuzione scelti dai visitatori sembrano più o meno simili nei due dataset fatta eccezione per il dato inerente alle prenotazioni avvenute offline tramite TA/TO (decisamente più alto nel traindataset).
"Aviation" e "complementary" hanno un numero di casi estremamente più basso mentre le prenotazioni presso agenzie online rappresentano circa la metà dei casi in entrambi i datset.
La media delle cancellazioni è quasi raddoppiata per quanto riguarda i gruppi mentre è dimezzata per chi prenota direttamente.

Controllare numero di prenotazioni precedenti e cancellazioni precedenti (fino a qui niko)

In [ ]:
train.groupby(train["previous_cancellations"]).count()

hotel  is_canceled  lead_time  arrival_date_year  \
previous_cancellations                                                     
0                       54936        54936      54936              54936   
1                        1595         1595       1595               1595   
2                          48           48         48                 48   
3                          51           51         51                 51   
4                          12           12         12                 12   
5                          13           13         13                 13   
6                           7            7          7                  7   
11                         33           33         33                 33   
13                         12           12         12                 12   

                        arrival_date_month  arrival_date_week_number  \
previous_cancellations                                                 
0                                    54936                     54936   
1                                     1595                      1595   
2                                       48                        48   
3                                       51                        51   
4                                       12                        12   
5                                       13                        13   
6                                        7                         7   
11                                      33                        33   
13                                      12                        12   

                        arrival_date_day_of_month  stays_in_weekend_nights  \
previous_cancellations                                                       
0                                           54936                    54936   
1                                            1595                     1595   
2                                              48                       48   
3                                              51                       51   
4                                              12                       12   
5                                              13                       13   
6                                               7                        7   
11                                             33                       33   
13                                             12                       12   

                        stays_in_week_nights  adults  ...  deposit_type  \
previous_cancellations                                ...                 
0                                      54936   54936  ...         54936   
1                                       1595    1595  ...          1595   
2                                         48      48  ...            48   
3                                         51      51  ...            51   
4                                         12      12  ...            12   
5                                         13      13  ...            13   
6                                          7       7  ...             7   
11                                        33      33  ...            33   
13                                        12      12  ...            12   

                        agent  company  days_in_waiting_list  customer_type  \
previous_cancellations                                                        
0                       54936    54936                 54936          54936   
1                        1595     1595                  1595           1595   
2                          48       48                    48             48   
3                          51       51                    51             51   
4                          12       12                    12             12   
5                          13       13                    13             13   
6                           7        7                     7              7  

In [ ]:
test.groupby(test["previous_cancellations"]).count()

hotel  is_canceled  lead_time  arrival_date_year  \
previous_cancellations                                                     
0                       40409        40409      40409              40409   
1                         195          195        195                195   
2                          37           37         37                 37   
3                           6            6          6                  6   
4                          19           19         19                 19   
5                           6            6          6                  6   
6                          15           15         15                 15   

                        arrival_date_month  arrival_date_week_number  \
previous_cancellations                                                 
0                                    40409                     40409   
1                                      195                       195   
2                                       37                        37   
3                                        6                         6   
4                                       19                        19   
5                                        6                         6   
6                                       15                        15   

                        arrival_date_day_of_month  stays_in_weekend_nights  \
previous_cancellations                                                       
0                                           40409                    40409   
1                                             195                      195   
2                                              37                       37   
3                                               6                        6   
4                                              19                       19   
5                                               6                        6   
6                                              15                       15   

                        stays_in_week_nights  adults  ...  deposit_type  \
previous_cancellations                                ...                 
0                                      40409   40409  ...         40409   
1                                        195     195  ...           195   
2                                         37      37  ...            37   
3                                          6       6  ...             6   
4                                         19      19  ...            19   
5                                          6       6  ...             6   
6                                         15      15  ...            15   

                        agent  company  days_in_waiting_list  customer_type  \
previous_cancellations                                                        
0                       40409    40409                 40409          40409   
1                         195      195                   195            195   
2                          37       37                    37             37   
3                           6        6                     6              6   
4                          19       19                    19             19   
5                           6        6                     6              6   
6                          15       15                    15             15   

                          adr  required_car_parking_spaces  \
previous_cancellations                                       
0                       40409                        40409   
1                         195                          195   
2                          37                           37   
3                           6                            6   
4                          19                           19   
5                           6                            6   
6                          15                           15   

                        total_of_special

In [ ]:
train.groupby(train["previous_bookings_not_canceled"]).count()

hotel  is_canceled  lead_time  \
previous_bookings_not_canceled                                  
0                               54827        54827      54827   
1                                 777          777        777   
2                                 289          289        289   
3                                 183          183        183   
4                                 138          138        138   
5                                 110          110        110   
6                                  62           62         62   
7                                  43           43         43   
8                                  36           36         36   
9                                  27           27         27   
10                                 22           22         22   
11                                 18           18         18   
12                                 15           15         15   
13                                 10           10         10   
14                                 11           11         11   
15                                 11           11         11   
16                                 10           10         10   
17                                  9            9          9   
18                                  9            9          9   
19                                  8            8          8   
20                                  9            9          9   
21                                  9            9          9   
22                                  9            9          9   
23                                  4            4          4   
24                                  4            4          4   
25                                 11           11         11   
26                                  2            2          2   
27                                  4            4          4   
28                                  3            3          3   
29                                  3            3          3   
30                                  2            2          2   
31                                  2            2          2   
32                                  2            2          2   
33                                  1            1          1   
34                                  1            1          1   
35                                  1            1          1   
36                                  1            1          1   
37                                  1            1          1   
38                                  1            1          1   
39                                  1            1          1   
40                                  1            1          1   
41                                  1            1          1   
42                                  1            1          1   
43                                  1            1          1   
44                                  2            2          2   
45                                  1            1          1   
46                                  1            1          1   
47                                  1            1          1   
48                                  2            2          2   
49                                  1            1          1   
50                                  1            1          1   
51                                  1            1          1   
52                                  1            1          1   
53                                  1            1          1   
54                                  1            1          1   
55                                  1            1          1   
56                                  1            1          1   
57                                  1            1          1   
58                                  1            1          1   

                                arrival_date_year  arrival_date_mo

In [ ]:
test.groupby(test["previous_bookings_not_canceled"]).count()

hotel  is_canceled  lead_time  \
previous_bookings_not_canceled                                  
0                               39259        39259      39259   
1                                 590          590        590   
2                                 231          231        231   
3                                 122          122        122   
4                                  80           80         80   
5                                  60           60         60   
6                                  46           46         46   
7                                  39           39         39   
8                                  30           30         30   
9                                  30           30         30   
10                                 29           29         29   
11                                 23           23         23   
12                                 21           21         21   
13                                 19           19         19   
14                                 16           16         16   
15                                 10           10         10   
16                                 10           10         10   
17                                  7            7          7   
18                                  5            5          5   
19                                  5            5          5   
20                                  3            3          3   
21                                  3            3          3   
22                                  1            1          1   
23                                  3            3          3   
24                                  5            5          5   
25                                  6            6          6   
26                                  5            5          5   
27                                  5            5          5   
28                                  4            4          4   
29                                  3            3          3   
30                                  2            2          2   
58                                  1            1          1   
59                                  1            1          1   
60                                  1            1          1   
61                                  1            1          1   
62                                  1            1          1   
63                                  1            1          1   
64                                  1            1          1   
65                                  1            1          1   
66                                  1            1          1   
67                                  1            1          1   
68                                  1            1          1   
69                                  1            1          1   
70                                  1            1          1   
71                                  1            1          1   
72                                  1            1          1   

                                arrival_date_year  arrival_date_month  \
previous_bookings_not_canceled                                          
0                                           39259               39259   
1                                             590                 590   
2                                             231                 231   
3                                             122                 122   
4                                              80                  80   
5                                              60                  60   
6                                              46                  46   
7                                              39                  39   
8                                              30                  30   
9                                              30                  30   
10                                 

In [ ]:
train["prenotazioni_precedenti"] = train["previous_bookings_not_canceled"] + train["previous_cancellations"]
train.groupby(train["prenotazioni_precedenti"]).count()

hotel  is_canceled  lead_time  arrival_date_year  \
prenotazioni_precedenti                                                     
0                        53380        53380      53380              53380   
1                         2162         2162       2162               2162   
2                          302          302        302                302   
3                          179          179        179                179   
4                          125          125        125                125   
5                          102          102        102                102   
6                           77           77         77                 77   
7                           53           53         53                 53   
8                           43           43         43                 43   
9                           30           30         30                 30   
10                          23           23         23                 23   
11                          20           20         20                 20   
12                          18           18         18                 18   
13                           9            9          9                  9   
14                          22           22         22                 22   
15                          16           16         16                 16   
16                          14           14         14                 14   
17                           9            9          9                  9   
18                           9            9          9                  9   
19                           8            8          8                  8   
20                           8            8          8                  8   
21                          10           10         10                 10   
22                           8            8          8                  8   
23                           7            7          7                  7   
24                           4            4          4                  4   
25                           5            5          5                  5   
26                           4            4          4                  4   
27                           3            3          3                  3   
28                           2            2          2                  2   
29                           3            3          3                  3   
30                           4            4          4                  4   
31                           3            3          3                  3   
32                           3            3          3                  3   
33                           4            4          4                  4   
34                           1            1          1                  1   
35                           1            1          1                  1   
36                           9            9          9                  9   
37                           1            1          1                  1   
38                           1            1          1                  1   
39                           1            1          1                  1   
40                           1            1          1                  1   
41                           1            1          1                  1   
42                           1            1          1                  1   
43                           1            1          1                  1   
44                           1            1          1                  1   
45                           1            1          1                  1   
46                           1            1          1                  1   
47                           1            1          1                  1   
48                           1            1          1                  1   
49                           1            1          1                  1   
50                   

In [ ]:
test["prenotazioni_precedenti"] = test["previous_bookings_not_canceled"] + test["previous_cancellations"]
test.groupby(train["prenotazioni_precedenti"]).count()

hotel  is_canceled  lead_time  arrival_date_year  \
prenotazioni_precedenti                                                     
0                        37613        37613      37613              37613   
1                         2008         2008       2008               2008   
2                          271          271        271                271   
3                          161          161        161                161   
4                          107          107        107                107   
5                           93           93         93                 93   
6                           68           68         68                 68   
7                           49           49         49                 49   
8                           37           37         37                 37   
9                           28           28         28                 28   
10                          22           22         22                 22   
11                          19           19         19                 19   
12                          18           18         18                 18   
13                           9            9          9                  9   
14                          22           22         22                 22   
15                          16           16         16                 16   
16                          14           14         14                 14   
17                           9            9          9                  9   
18                           9            9          9                  9   
19                           8            8          8                  8   
20                           8            8          8                  8   
21                          10           10         10                 10   
22                           8            8          8                  8   
23                           7            7          7                  7   
24                           4            4          4                  4   
25                           5            5          5                  5   
26                           4            4          4                  4   
27                           3            3          3                  3   
28                           2            2          2                  2   
29                           3            3          3                  3   
30                           4            4          4                  4   
31                           3            3          3                  3   
32                           3            3          3                  3   
33                           4            4          4                  4   
34                           1            1          1                  1   
35                           1            1          1                  1   
36                           9            9          9                  9   
37                           1            1          1                  1   
38                           1            1          1                  1   
39                           1            1          1                  1   
40                           1            1          1                  1   
41                           1            1          1                  1   
42                           1            1          1                  1   
43                           1            1          1                  1   
44                           1            1          1                  1   
45                           1            1          1                  1   
46                           1            1          1                  1   
47                           1            1          1                  1   
48                           1            1          1                  1   
49                           1            1          1                  1   
50                   

In [ ]:
train.groupby(train["previous_bookings_not_canceled"])["is_canceled"].mean()

previous_bookings_not_canceled
0     0.368924
1     0.055341
2     0.038062
3     0.043716
4     0.072464
5     0.081818
6     0.048387
7     0.023256
8     0.055556
9     0.000000
10    0.136364
11    0.111111
12    0.200000
13    0.000000
14    0.000000
15    0.181818
16    0.000000
17    0.000000
18    0.000000
19    0.000000
20    0.000000
21    0.000000
22    0.000000
23    0.000000
24    0.000000
25    0.727273
26    0.000000
27    0.250000
28    0.000000
29    0.333333
30    0.000000
31    0.000000
32    0.000000
33    0.000000
34    0.000000
35    0.000000
36    0.000000
37    0.000000
38    0.000000
39    0.000000
40    0.000000
41    0.000000
42    0.000000
43    0.000000
44    0.500000
45    0.000000
46    0.000000
47    0.000000
48    0.500000
49    0.000000
50    0.000000
51    0.000000
52    0.000000
53    0.000000
54    0.000000
55    0.000000
56    0.000000
57    0.000000
58    1.000000
Name: is_canceled, dtype: float64

In [ ]:
test.groupby(test["previous_bookings_not_canceled"])["is_canceled"].mean()

previous_bookings_not_canceled
0     0.399272
1     0.049153
2     0.060606
3     0.040984
4     0.025000
5     0.016667
6     0.000000
7     0.076923
8     0.033333
9     0.000000
10    0.137931
11    0.130435
12    0.000000
13    0.105263
14    0.125000
15    0.000000
16    0.100000
17    0.142857
18    0.000000
19    0.000000
20    0.000000
21    0.000000
22    0.000000
23    0.000000
24    0.000000
25    0.000000
26    0.200000
27    0.200000
28    0.000000
29    0.000000
30    0.000000
58    0.000000
59    0.000000
60    0.000000
61    0.000000
62    0.000000
63    0.000000
64    0.000000
65    0.000000
66    0.000000
67    0.000000
68    0.000000
69    0.000000
70    0.000000
71    0.000000
72    0.000000
Name: is_canceled, dtype: float64

In [ ]:
train.groupby(train["previous_cancellations"])["is_canceled"].mean()

previous_cancellations
0     0.342799
1     0.909718
2     0.312500
3     0.196078
4     0.083333
5     0.153846
6     1.000000
11    0.242424
13    0.916667
Name: is_canceled, dtype: float64

In [ ]:
test.groupby(test["previous_cancellations"])["is_canceled"].mean()

previous_cancellations
0    0.388453
1    0.174359
2    0.162162
3    0.333333
4    0.315789
5    0.000000
6    0.000000
Name: is_canceled, dtype: float64

In [ ]:
train.groupby(train["prenotazioni_precedenti"])["is_canceled"].mean()

prenotazioni_precedenti
0     0.352154
1     0.663275
2     0.076159
3     0.039106
4     0.056000
5     0.078431
6     0.220779
7     0.094340
8     0.046512
9     0.033333
10    0.086957
11    0.050000
12    0.222222
13    0.000000
14    0.545455
15    0.125000
16    0.000000
17    0.000000
18    0.111111
19    0.000000
20    0.000000
21    0.000000
22    0.000000
23    0.000000
24    0.000000
25    0.000000
26    0.000000
27    0.000000
28    0.000000
29    0.333333
30    0.250000
31    0.000000
32    0.000000
33    0.000000
34    0.000000
35    0.000000
36    0.888889
37    0.000000
38    0.000000
39    0.000000
40    0.000000
41    0.000000
42    0.000000
43    0.000000
44    0.000000
45    0.000000
46    0.000000
47    1.000000
48    0.000000
49    0.000000
50    0.000000
51    0.000000
53    0.500000
54    0.000000
55    0.000000
56    0.000000
57    0.000000
58    0.000000
59    0.000000
60    0.000000
61    0.000000
62    0.000000
64    1.000000
Name: is_canceled, dtype: float

In [ ]:
test.groupby(test["prenotazioni_precedenti"])["is_canceled"].mean()

prenotazioni_precedenti
0     0.399256
1     0.024561
2     0.093220
3     0.073770
4     0.067416
5     0.051724
6     0.000000
7     0.032258
8     0.031250
9     0.032258
10    0.076923
11    0.130435
12    0.000000
13    0.000000
14    0.055556
15    0.200000
16    0.214286
17    0.100000
18    0.000000
19    0.000000
20    0.000000
21    0.333333
22    0.000000
23    0.000000
24    0.000000
25    0.000000
26    0.000000
27    0.200000
28    0.000000
29    0.000000
30    0.333333
31    0.000000
32    0.000000
33    0.000000
34    0.000000
64    0.000000
65    0.000000
66    0.000000
67    0.000000
68    0.000000
69    0.000000
70    0.000000
71    0.000000
72    0.000000
73    0.000000
74    0.000000
75    0.000000
76    0.000000
77    0.000000
78    0.000000
Name: is_canceled, dtype: float64

Il numero di prenotazioni fatte da persone che avevano già fatto una prenotazione presso gli hotel è relativamente basso. La media relativa alle cancellazioni sembra abbassarsi drasticamente per chi aveva già fatto almeno una prenotazione.

Controllare la distribuzione in base al tipo di hotel selezionato

In [ ]:
train.groupby(train["hotel"]).count()

is_canceled  lead_time  arrival_date_year  arrival_date_month  \
hotel                                                                  
0            38140      38140              38140               38140   
1            18567      18567              18567               18567   

       arrival_date_week_number  arrival_date_day_of_month  \
hotel                                                        
0                         38140                      38140   
1                         18567                      18567   

       stays_in_weekend_nights  stays_in_week_nights  adults  children  ...  \
hotel                                                                   ...   
0                        38140                 38140   38140     38140  ...   
1                        18567                 18567   18567     18567  ...   

       assigned_room_type  booking_changes  deposit_type  agent  company  \
hotel                                                                      
0                   38140            38140         38140  38140    38140   
1                   18567            18567         18567  18567    18567   

       days_in_waiting_list  customer_type    adr  \
hotel                                               
0                     38140          38140  38140   
1                     18567          18567  18567   

       required_car_parking_spaces  total_of_special_requests  
hotel                                                          
0                            38140                      38140  
1                            18567                      18567  

[2 rows x 29 columns]

In [ ]:
test.groupby(test["hotel"]).count()

is_canceled  lead_time  arrival_date_year  arrival_date_month  \
hotel                                                                  
0            27508      27508              27508               27508   
1            13179      13179              13179               13179   

       arrival_date_week_number  arrival_date_day_of_month  \
hotel                                                        
0                         27508                      27508   
1                         13179                      13179   

       stays_in_weekend_nights  stays_in_week_nights  adults  children  ...  \
hotel                                                                   ...   
0                        27508                 27508   27508     27508  ...   
1                        13179                 13179   13179     13179  ...   

       assigned_room_type  booking_changes  deposit_type  agent  company  \
hotel                                                                      
0                   27508            27508         27508  27508    27508   
1                   13179            13179         13179  13179    13179   

       days_in_waiting_list  customer_type    adr  \
hotel                                               
0                     27508          27508  27508   
1                     13179          13179  13179   

       required_car_parking_spaces  total_of_special_requests  
hotel                                                          
0                            27508                      27508  
1                            13179                      13179  

[2 rows x 29 columns]

In [ ]:
media_hotel = train.groupby(train["hotel"]).mean()
print(media_hotel)

       is_canceled   lead_time  arrival_date_year  arrival_date_month  \
hotel                                                                   
0         0.403959  108.099948             2016.0            6.855113   
1         0.265525   92.127861             2016.0            6.586955   

       arrival_date_week_number  arrival_date_day_of_month  \
hotel                                                        
0                     28.838437                  15.885107   
1                     27.677008                  15.964507   

       stays_in_weekend_nights  stays_in_week_nights    adults  children  ...  \
hotel                                                                     ...   
0                     0.776796              2.186523  1.850236  0.100000  ...   
1                     1.134701              2.969247  1.852534  0.112781  ...   

       assigned_room_type  booking_changes  deposit_type      agent  \
hotel                                                         

ci sono più cancellazioni in city hotel (0) che in resort hotel (1)

Controllare la distribuzione in base ai giorni in attesa

In [ ]:
train.groupby(train["days_in_waiting_list"]).count()

hotel  is_canceled  lead_time  arrival_date_year  \
days_in_waiting_list                                                     
0                     53958        53958      53958              53958   
1                         8            8          8                  8   
2                         3            3          3                  3   
3                        59           59         59                 59   
4                        20           20         20                 20   
...                     ...          ...        ...                ...   
236                      35           35         35                 35   
259                      10           10         10                 10   
330                      15           15         15                 15   
379                      15           15         15                 15   
391                      45           45         45                 45   

                      arrival_date_month  arrival_date_week_number  \
days_in_waiting_list                                                 
0                                  53958                     53958   
1                                      8                         8   
2                                      3                         3   
3                                     59                        59   
4                                     20                        20   
...                                  ...                       ...   
236                                   35                        35   
259                                   10                        10   
330                                   15                        15   
379                                   15                        15   
391                                   45                        45   

                      arrival_date_day_of_month  stays_in_weekend_nights  \
days_in_waiting_list                                                       
0                                         53958                    53958   
1                                             8                        8   
2                                             3                        3   
3                                            59                       59   
4                                            20                       20   
...                                         ...                      ...   
236                                          35                       35   
259                                          10                       10   
330                                          15                       15   
379                                          15                       15   
391                                          45                       45   

                      stays_in_week_nights  adults  ...  booking_changes  \
days_in_waiting_list                                ...                    
0                                    53958   53958  ...            53958   
1                                        8       8  ...                8   
2                                        3       3  ...                3   
3                                       59      59  ...               59   
4                                       20      20  ...               20   
...                                    ...     ...  ...              ...   
236                                     35      35  ...               35   
259                                     10      10  ...               10   
330                                     15      15  ...               15   
379                                     15      15  ...               15   
391                                     45      45  ...               45   

                      deposit_type  agent  company  customer_type    adr  \
days_in_waiting_list                                                       
0                 

In [ ]:
waiting_people = tot_train - 53958
print(waiting_people)

2750


In [ ]:
test.groupby(test["days_in_waiting_list"]).count()

hotel  is_canceled  lead_time  arrival_date_year  \
days_in_waiting_list                                                     
0                     40487        40487      40487              40487   
1                         4            4          4                  4   
2                         2            2          2                  2   
4                         5            5          5                  5   
5                         6            6          6                  6   
...                     ...          ...        ...                ...   
165                       1            1          1                  1   
175                       1            1          1                  1   
183                       1            1          1                  1   
185                       2            2          2                  2   
223                       1            1          1                  1   

                      arrival_date_month  arrival_date_week_number  \
days_in_waiting_list                                                 
0                                  40487                     40487   
1                                      4                         4   
2                                      2                         2   
4                                      5                         5   
5                                      6                         6   
...                                  ...                       ...   
165                                    1                         1   
175                                    1                         1   
183                                    1                         1   
185                                    2                         2   
223                                    1                         1   

                      arrival_date_day_of_month  stays_in_weekend_nights  \
days_in_waiting_list                                                       
0                                         40487                    40487   
1                                             4                        4   
2                                             2                        2   
4                                             5                        5   
5                                             6                        6   
...                                         ...                      ...   
165                                           1                        1   
175                                           1                        1   
183                                           1                        1   
185                                           2                        2   
223                                           1                        1   

                      stays_in_week_nights  adults  ...  booking_changes  \
days_in_waiting_list                                ...                    
0                                    40487   40487  ...            40487   
1                                        4       4  ...                4   
2                                        2       2  ...                2   
4                                        5       5  ...                5   
5                                        6       6  ...                6   
...                                    ...     ...  ...              ...   
165                                      1       1  ...                1   
175                                      1       1  ...                1   
183                                      1       1  ...                1   
185                                      2       2  ...                2   
223                                      1       1  ...                1   

                      deposit_type  agent  company  customer_type    adr  \
days_in_waiting_list                                                       
0                 

In [ ]:
waiting_people_test = tot_test - 40487
print(waiting_people_test)

200


In [35]:
media_giorni_in_lista_attesa = train.groupby(train["days_in_waiting_list"]).count()
print(media_giorni_in_lista_attesa)

                      hotel  is_canceled  lead_time  arrival_date_year  \
days_in_waiting_list                                                     
0                     53958        53958      53958              53958   
1                         8            8          8                  8   
2                         3            3          3                  3   
3                        59           59         59                 59   
4                        20           20         20                 20   
...                     ...          ...        ...                ...   
236                      35           35         35                 35   
259                      10           10         10                 10   
330                      15           15         15                 15   
379                      15           15         15                 15   
391                      45           45         45                 45   

                      arrival_date_mo

I due dataset differiscono molto nei valori relativi alle persone che sono rimaste in lista d'attesa, difatti, nel train dataset abbiamo 2750 persone con valori che vanno da 0 a 391 giorni in lista d'attesa, nel secondo, invece, i casi scendono a 200 con valori da 0 a 223.

controllare la distribuzione in base al "customer Type". (fino a qui Salvo)

In [ ]:
train.groupby(train["customer_type"]).count()

hotel  is_canceled  lead_time  arrival_date_year  \
customer_type                                                     
0                756          756        756                756   
1                167          167        167                167   
2              44391        44391      44391              44391   
3              11393        11393      11393              11393   

               arrival_date_month  arrival_date_week_number  \
customer_type                                                 
0                             756                       756   
1                             167                       167   
2                           44391                     44391   
3                           11393                     11393   

               arrival_date_day_of_month  stays_in_weekend_nights  \
customer_type                                                       
0                                    756                      756   
1                                    167                      167   
2                                  44391                    44391   
3                                  11393                    11393   

               stays_in_week_nights  adults  ...  reserved_room_type  \
customer_type                                ...                       
0                               756     756  ...                 756   
1                               167     167  ...                 167   
2                             44391   44391  ...               44391   
3                             11393   11393  ...               11393   

               assigned_room_type  booking_changes  deposit_type  agent  \
customer_type                                                             
0                             756              756           756    756   
1                             167              167           167    167   
2                           44391            44391         44391  44391   
3                           11393            11393         11393  11393   

               company  days_in_waiting_list    adr  \
customer_type                                         
0                  756                   756    756   
1                  167                   167    167   
2                44391                 44391  44391   
3                11393                 11393  11393   

               required_car_parking_spaces  total_of_special_requests  
customer_type                                                          
0                                      756                        756  
1                                      167                        167  
2                                    44391                      44391  
3                                    11393                      11393  

[4 rows x 29 columns]

In [ ]:
test.groupby(test["customer_type"]).count()

hotel  is_canceled  lead_time  arrival_date_year  \
customer_type                                                     
0                662          662        662                662   
1                218          218        218                218   
2              33791        33791      33791              33791   
3               6016         6016       6016               6016   

               arrival_date_month  arrival_date_week_number  \
customer_type                                                 
0                             662                       662   
1                             218                       218   
2                           33791                     33791   
3                            6016                      6016   

               arrival_date_day_of_month  stays_in_weekend_nights  \
customer_type                                                       
0                                    662                      662   
1                                    218                      218   
2                                  33791                    33791   
3                                   6016                     6016   

               stays_in_week_nights  adults  ...  reserved_room_type  \
customer_type                                ...                       
0                               662     662  ...                 662   
1                               218     218  ...                 218   
2                             33791   33791  ...               33791   
3                              6016    6016  ...                6016   

               assigned_room_type  booking_changes  deposit_type  agent  \
customer_type                                                             
0                             662              662           662    662   
1                             218              218           218    218   
2                           33791            33791         33791  33791   
3                            6016             6016          6016   6016   

               company  days_in_waiting_list    adr  \
customer_type                                         
0                  662                   662    662   
1                  218                   218    218   
2                33791                 33791  33791   
3                 6016                  6016   6016   

               required_car_parking_spaces  total_of_special_requests  
customer_type                                                          
0                                      662                        662  
1                                      218                        218  
2                                    33791                      33791  
3                                     6016                       6016  

[4 rows x 29 columns]

In [34]:
media_customer_type = train.groupby(train["customer_type"]).count()
print(media_customer_type)

               hotel  is_canceled  lead_time  arrival_date_year  \
customer_type                                                     
0                756          756        756                756   
1                167          167        167                167   
2              44391        44391      44391              44391   
3              11393        11393      11393              11393   

               arrival_date_month  arrival_date_week_number  \
customer_type                                                 
0                             756                       756   
1                             167                       167   
2                           44391                     44391   
3                           11393                     11393   

               arrival_date_day_of_month  stays_in_weekend_nights  \
customer_type                                                       
0                                    756                      756   
1          

Controllare la distribuzione di dati in base al tipo di prenotazione

In [36]:
train.groupby(train["distribution_channel"]).count()

hotel  is_canceled  lead_time  arrival_date_year  \
distribution_channel                                                     
0                      3292         3292       3292               3292   
1                      6799         6799       6799               6799   
2                       104          104        104                104   
3                     46512        46512      46512              46512   

                      arrival_date_month  arrival_date_week_number  \
distribution_channel                                                 
0                                   3292                      3292   
1                                   6799                      6799   
2                                    104                       104   
3                                  46512                     46512   

                      arrival_date_day_of_month  stays_in_weekend_nights  \
distribution_channel                                                       
0                                          3292                     3292   
1                                          6799                     6799   
2                                           104                      104   
3                                         46512                    46512   

                      stays_in_week_nights  adults  ...  assigned_room_type  \
distribution_channel                                ...                       
0                                     3292    3292  ...                3292   
1                                     6799    6799  ...                6799   
2                                      104     104  ...                 104   
3                                    46512   46512  ...               46512   

                      booking_changes  deposit_type  agent  company  \
distribution_channel                                                  
0                                3292          3292   3292     3292   
1                                6799          6799   6799     6799   
2                                 104           104    104      104   
3                               46512         46512  46512    46512   

                      days_in_waiting_list  customer_type    adr  \
distribution_channel                                               
0                                     3292           3292   3292   
1                                     6799           6799   6799   
2                                      104            104    104   
3                                    46512          46512  46512   

                      required_car_parking_spaces  total_of_special_requests  
distribution_channel                                                          
0                                            3292                       3292  
1                                            6799                       6799  
2                                             104                        104  
3                                           46512                      46512  

[4 rows x 29 columns]

In [37]:
test.groupby(test["distribution_channel"]).count()

hotel  is_canceled  lead_time  arrival_date_year  \
distribution_channel                                                     
0                      1921         1921       1921               1921   
1                      5061         5061       5061               5061   
2                        88           88         88                 88   
3                     33617        33617      33617              33617   

                      arrival_date_month  arrival_date_week_number  \
distribution_channel                                                 
0                                   1921                      1921   
1                                   5061                      5061   
2                                     88                        88   
3                                  33617                     33617   

                      arrival_date_day_of_month  stays_in_weekend_nights  \
distribution_channel                                                       
0                                          1921                     1921   
1                                          5061                     5061   
2                                            88                       88   
3                                         33617                    33617   

                      stays_in_week_nights  adults  ...  assigned_room_type  \
distribution_channel                                ...                       
0                                     1921    1921  ...                1921   
1                                     5061    5061  ...                5061   
2                                       88      88  ...                  88   
3                                    33617   33617  ...               33617   

                      booking_changes  deposit_type  agent  company  \
distribution_channel                                                  
0                                1921          1921   1921     1921   
1                                5061          5061   5061     5061   
2                                  88            88     88       88   
3                               33617         33617  33617    33617   

                      days_in_waiting_list  customer_type    adr  \
distribution_channel                                               
0                                     1921           1921   1921   
1                                     5061           5061   5061   
2                                       88             88     88   
3                                    33617          33617  33617   

                      required_car_parking_spaces  total_of_special_requests  
distribution_channel                                                          
0                                            1921                       1921  
1                                            5061                       5061  
2                                              88                         88  
3                                           33617                      33617  

[4 rows x 29 columns]

In [38]:
media_canale_distribuzione = train.groupby(train["distribution_channel"]).count()
print(media_canale_distribuzione)

                      hotel  is_canceled  lead_time  arrival_date_year  \
distribution_channel                                                     
0                      3292         3292       3292               3292   
1                      6799         6799       6799               6799   
2                       104          104        104                104   
3                     46512        46512      46512              46512   

                      arrival_date_month  arrival_date_week_number  \
distribution_channel                                                 
0                                   3292                      3292   
1                                   6799                      6799   
2                                    104                       104   
3                                  46512                     46512   

                      arrival_date_day_of_month  stays_in_weekend_nights  \
distribution_channel                                      

Controllare la distribuzione dei dati in base alla durata del soggiorno (fare una colonna "days" (weekend + week))

Controllare la distribuzione di dati in base al tipo di prenotazione e pasti prenotati (b&b etc.)

Controllare il numero di cancellazioni in base al deposito fatto oppure no (deposit_type)

Controllare la distribuzione di chi ha richiesto un parcheggio e chi no